.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. abcmint_qt test_abcmint_qt
clean: FORCE
	$(MAKE) -C .. abcmint_qt_clean test_abcmint_qt_clean
check: FORCE
	$(MAKE) -C .. test_abcmint_qt_check
abcmint-qt abcmint-qt.exe: FORCE
	 $(MAKE) -C .. abcmint_qt
apk: FORCE
	$(MAKE) -C .. abcmint_qt_apk
